# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: LosPingheros.com
email: info@hectiq.games
description: >- # this means to ignore newlines until "baseurl:"
  Los Pingheros is a multiplayer fighting game that can host up to 8 players online or locally. 
  Dive into the vibrant colors of Mexico, draped in a unique snowy mantle, and engage in the action alone or with your friends. 
  Your goal will be to become the ultimate Pinghero by knocking your opponents out of the arena using the snow!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
privacy_policy: /privacy_policy
twitter_username: jekyllrb
github_username:  jekyll


keyart_url: /assets/images/artworks/LosPingheros_KeyArt_Base.jpg
keylogo_url: /assets/images/logos/Los_Pingheros_Logo.png
keylogo_url_small: /assets/images/logos/Los_Pingheros_Logo_small.png
favicon_url: /assets/images/logos/Los_Pingheros_Logo_favicon.png
hectiq_url: "https://www.hectiq.games"
hectiq_logo_url: /assets/images/logos/hectiq_logo.png

presskit_url: "https://hectiq.notion.site/LOS-PINGHEROS-Press-Kit-c325e93187ca4929bf74cc70e9f91ff2?pvs=4"
reddit_url: "https://www.reddit.com/user/HectiqGames"
linkedin_url: "https://www.linkedin.com/company/hectiq-games"
facebook_url: "https://www.facebook.com/profile.php?id=61557780671331&locale=fr_FR"
twitter_url: "https://twitter.com/HectiqGames"
youtube_url: "https://www.youtube.com/channel/UCjDdt0owalCNcdw0f2_TfDQ"
instagram_url: "https://www.instagram.com/hectiqgames/"
tiktok_url: "https://www.tiktok.com/@hectiqgames"


# Build settings
# theme: minima
plugins:
  - jekyll-feed


exclude:
  - Gemfile
  - Gemfile.lock
  - template/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
